#!/bin/bash

#-----------
# Configurations
#-----------

MONIT_PORT=${MONIT_PORT-4001}
MONIT_HOST=${MONIT_HOST-127.0.0.1}
MONIT_USER=${MONIT_USER-monit}
MONIT_PASSWORD=${MONIT_PASSWORD-monit}
MONIT_CONF_DIR=${MONIT_CONF_DIR-/etc/monit/conf.d}

#-----------
# Install Script
#-----------

DESIRED_VERSION="5.5.1"
BASEDIR=./submodules/monit/files

if [[ "`which monit 2> /dev/null`" == "" ]]; then
  MONIT_NAME=monit-$DESIRED_VERSION
  MONIT_EXT='linux-x86'
  MACHINE=$(uname -m)
  if [[ "$MACHINE" == 'x86_64' ]]; then
    MONIT_EXT='linux-x64'
  fi
  (cd $BASEDIR && tar zxf ./$MONIT_NAME-$MONIT_EXT.tar.gz)
  cp $BASEDIR/$MONIT_NAME/bin/monit /usr/local/bin/monit
fi

cp $BASEDIR/monit_default /etc/default/monit
cp $BASEDIR/monit.conf /etc/init/monit.conf

cp $BASEDIR/monitrc /etc/monitrc
sed -i s/@MONIT_PORT@/$MONIT_PORT/g /etc/monitrc
sed -i s/@MONIT_HOST@/$MONIT_HOST/g /etc/monitrc
sed -i s/@MONIT_USER@/$MONIT_USER/g /etc/monitrc
sed -i s/@MONIT_PASSWORD@/$MONIT_PASSWORD/g /etc/monitrc

chmod 700 /etc/monitrc

mkdir -p $MONIT_CONF_DIR
initctl reload-configuration

MONIT_STATUS=`status monit`
if [[ "$MONIT_STATUS" == "monit stop/waiting" ]]; then
  start monit
fi
